[package]
name = "noise_visualizer"
version = "0.1.0"
authors = ["Tyler Reisinger <reisinger.tyler@gmail.com>"]

[dependencies]
glium = "*"
noise_lib = { path="../../noise_lib/noise_lib" }
cgmath = "^0.16"
game_time = "0.2.0"
rand = "0.4"
image = "0.18"
